name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: "Build Changelog"
                id: build_changelog
                uses: mikepenz/release-changelog-builder-action@main
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    toTag: HEAD
    first-stage:
        needs: debug
        runs-on: ubuntu-latest
        steps:
            -   name: test
                run: echo 'CIA'
