name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Get next version
                uses: technote-space/get-next-version-action@v1
            -   run: |
                    echo "NEXT_VERSION: ${process.env.NEXT_VERSION}"

    first-stage:
        needs: debug
        runs-on: ubuntu-latest
        steps:
            -   name: test
                run: echo 'CIA'
