name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   id: compute_tag
                uses: craig-day/compute-tag@v10
                with:
                    github_token: ${{ github.token }}
            -   run: |
                    echo "next-tag: ${{ steps.compute_tag.outputs.next_tag }}

    first-stage:
        needs: debug
        runs-on: ubuntu-latest
        steps:
            -   name: test
                run: echo 'CIA'
