name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: nuuday/github-changelog-action@v1.0.0
                id: changelog
                with:
                    next_version: "1.0.0"
            - run: |
                echo ${{ steps.changelog.outputs.release_notes }}
    first-stage:
        needs: debug
        runs-on: ubuntu-latest
        steps:
            -   name: test
                run: echo 'CIA'
