name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: SOLIDSoftworks/semver-tags
                id: semver-tags
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
                    tag-prefix: 'v'
                    default-version: '0.0.1'
                    prerelease: 'alpha'
            -   run: |
                    echo "previous-version: ${{ steps.semver-tags.outputs.previous-version }}"
                    echo "core-version: ${{ steps.semver-tags.outputs.core-version }}"
                    echo "semantic-version: ${{ steps.semver-tags.outputs.semantic-version }}"

    first-stage:
        needs: debug
        runs-on: ubuntu-latest
        steps:
            -   name: test
                run: echo 'CIA'
