name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build Changelog
                id: github_release
                uses: mikepenz/release-changelog-builder-action@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   run: |
                    echo 1
                    fail here
                    echo 2
    first-stage:
        needs: debug
        runs-on: ubuntu-latest
        steps:
            -   name: test
                run: echo 'CIA'
