name: CI

on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: |
                    echo '{}' > package.json
            -   name: Changelog
                uses: scottbrenner/generate-changelog-action@master
                id: Changelog
    first-stage:
        needs: debug
        runs-on: ubuntu-latest
        steps:
            -   name: test
                run: echo 'CIA'
