# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [ main ]
        tags:
            - '*'
    pull_request:
        branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    release:
        types: [ published, created, edited ]
jobs:
    debug:
        name: Debug
        runs-on: ubuntu-latest
        steps:
            -   name: Dump env
                run: env | sort
            -   name: Dump GitHub context
                env:
                    GITHUB_CONTEXT: ${{ toJson(github) }}
                run: echo "$GITHUB_CONTEXT"
            -   name: Tag name
                run: echo "${{ github.event.release.tag_name }}"

